name: Build and deploy Python app to Azure Web App - enrollment-app-csec3
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r app/backend/requirements.txt
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            app/backend/
          !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: List deployed files
        run: ls -la
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C4E694E75EC42CE94C296EEB4663C11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEE0E8ACBFA8452281712798E1A99D55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_932F753CC9044FACA5AB85A352423267 }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'enrollment-app-csec3'
          slot-name: 'Production'
